import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  Index,
} from 'typeorm';

export enum AuditAction {
  // Payments
  PAYMENT_INTENT_CREATED = 'PAYMENT_INTENT_CREATED',
  PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_EXPIRED = 'PAYMENT_EXPIRED',

  // Refunds
  REFUND_REQUESTED = 'REFUND_REQUESTED',
  REFUND_APPROVED = 'REFUND_APPROVED',
  REFUND_REJECTED = 'REFUND_REJECTED',

  // Escrow
  ESCROW_CREATED = 'ESCROW_CREATED',
  ESCROW_RELEASED = 'ESCROW_RELEASED',

  // Events
  EVENT_PUBLISHED = 'EVENT_PUBLISHED',
  EVENT_CANCELLED = 'EVENT_CANCELLED',
  EVENT_COMPLETED = 'EVENT_COMPLETED',

  // Age Verification
  AGE_VERIFIED = 'AGE_VERIFIED',
  AGE_RESTRICTION_SET = 'AGE_RESTRICTION_SET',

  // Resale Marketplace
  RESALE_LISTED = 'RESALE_LISTED',
  RESALE_BOUGHT = 'RESALE_BOUGHT',
  RESALE_CANCELLED = 'RESALE_CANCELLED',

  // Recommendations
  PREFERENCES_UPDATED = 'PREFERENCES_UPDATED',
  RECOMMENDATIONS_GENERATED = 'RECOMMENDATIONS_GENERATED',

  // Mobile Wallet
  MOBILE_PAYMENT_PROCESSED = 'MOBILE_PAYMENT_PROCESSED',
  MOBILE_PAYMENT_FAILED = 'MOBILE_PAYMENT_FAILED',

  // Insurance
  INSURANCE_PURCHASED = 'INSURANCE_PURCHASED',
  INSURANCE_CLAIM_PROCESSED = 'INSURANCE_CLAIM_PROCESSED',

  // Reviews
  REVIEW_SUBMITTED = 'REVIEW_SUBMITTED',
  REVIEW_VERIFIED = 'REVIEW_VERIFIED',
  REVIEW_REJECTED = 'REVIEW_REJECTED',
  REPUTATION_RECALCULATED = 'REPUTATION_RECALCULATED',

  // IoT Venue Capacity
  IOT_SENSOR_REGISTERED = 'IOT_SENSOR_REGISTERED',
  CAPACITY_ALERT_FIRED = 'CAPACITY_ALERT_FIRED',
  CAPACITY_LIMIT_UPDATED = 'CAPACITY_LIMIT_UPDATED',

  // Gamification
  ACHIEVEMENT_CREATED = 'ACHIEVEMENT_CREATED',
  ACHIEVEMENT_AWARDED = 'ACHIEVEMENT_AWARDED',
  LEADERBOARD_UPDATED = 'LEADERBOARD_UPDATED',
  CHALLENGE_CREATED = 'CHALLENGE_CREATED',
  CHALLENGE_ACTIVATED = 'CHALLENGE_ACTIVATED',
}

@Index(['userId', 'action'])
@Entity('audit_logs')
export class AuditLog {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Index()
  @Column()
  action: string;

  @Index()
  @Column()
  userId: string;

  @Column({ nullable: true, type: 'varchar' })
  resourceId: string | null;

  @Column({ type: 'jsonb', nullable: true })
  metadata: Record<string, unknown> | null;

  @CreateDateColumn()
  createdAt: Date;
}
